/* =============================================================
   words-data.js — Single source of truth for the Akaltye lexicon

   WHY:  Shared by both words.js (word list page) and
         practice.js (quiz engine) so there is only one
         place to add, edit or remove words.
   HOW:  ES module export — import with:
           import { WORDS } from './words-data.js';
   WHAT: 325 Arrernte words with phonetic, part of speech,
         definitions, example sentences and category tags.
   ============================================================= */

export const WORDS = [
  {
    word:       "akngwelye artnwere",
    phonetic:   "ug-NGWEL-yeh art-NWER-eh",
    pos:        "noun",
    definition: ["dingo"],
    tags:       ["advanced", "animals"],
    examples:   [],
  },
  {
    word:       "ltyentye apurte",
    phonetic:   "LCHEN-cheh ub-ORT-eh",
    pos:        "noun",
    definition: ["Santa Teresa"],
    tags:       ["advanced", "country", "place names"],
    examples:   [],
  },
  {
    word:       "irrkentye-akerte",
    phonetic:   "irk-EN-cheh ug-ERT-eh",
    pos:        "phrase",
    definition: ["regarding the law/rules"],
    tags:       ["advanced", "culture"],
    examples:   [],
  },
  {
    word:       "alye",
    phonetic:   "UL-yeh",
    pos:        "noun",
    definition: ["boomerang (Central Arrernte)"],
    tags:       ["advanced", "culture", "objects"],
    examples:   [],
    notes:      "Eastern Arrernte form: ilye",
  },
  {
    word:       "ilye",
    phonetic:   "IL-yeh",
    pos:        "noun",
    definition: ["boomerang (Eastern Arrernte)"],
    tags:       ["advanced", "culture", "objects"],
    examples:   [],
    notes:      "Central Arrernte form: alye",
  },
  {
    word:       "amirre",
    phonetic:   "um-IRR-eh",
    pos:        "noun",
    definition: ["woomera, spear-thrower"],
    tags:       ["advanced", "culture", "objects"],
    examples:   [],
  },
  {
    word:       "urtne",
    phonetic:   "ORT-neh",
    pos:        "noun",
    definition: ["coolamon"],
    tags:       ["advanced", "culture", "objects"],
    examples:   [],
  },
  {
    word:       "altyerre",
    phonetic:   "ul-CHER-reh",
    pos:        "noun",
    definition: ["a dream; Dreaming"],
    tags:       ["advanced", "culture", "spiritual"],
    examples:   [],
  },
  {
    word:       "anherre",
    phonetic:   "un-HERR-eh",
    pos:        "noun",
    definition: ["husband's mother"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "ankele",
    phonetic:   "ung-GEL-eh",
    pos:        "noun",
    definition: ["male cross-cousin"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "awenhe",
    phonetic:   "uh-WEN-eh",
    pos:        "noun",
    definition: ["father's sister"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "ipmenhe",
    phonetic:   "ib-MEN-eh",
    pos:        "noun",
    definition: ["mother's mother; woman's daughter's child"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "aperle",
    phonetic:   "ub-ERL-eh",
    pos:        "noun",
    definition: ["father's mother, woman's son's child"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "arrenge",
    phonetic:   "uh-RENG-eh",
    pos:        "noun",
    definition: ["father's father, man's son's child"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "altyeye",
    phonetic:   "ul-CHEY-eh",
    pos:        "noun",
    definition: ["female cross-cousin"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "atnyatye",
    phonetic:   "ud-NYUCH-eh",
    pos:        "noun",
    definition: ["mother's brother"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "atyemeye",
    phonetic:   "uh-chem-EY-eh",
    pos:        "noun",
    definition: ["mother's father, man's daughter's child"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "anewe",
    phonetic:   "un-EW-eh",
    pos:        "noun",
    definition: ["husband or wife, spouse"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "ampatye",
    phonetic:   "um-BUCH-eh",
    pos:        "noun",
    definition: ["woman's child, sister's child"],
    tags:       ["advanced", "family"],
    examples:   [],
  },
  {
    word:       "alakenhe-kwenye",
    phonetic:   "ul-AK-en-eh GWEN-yeh",
    pos:        "phrase",
    definition: ["without being like this"],
    tags:       ["advanced", "grammar"],
    examples:   [],
  },
  {
    word:       "irrtnye",
    phonetic:   "IRT-nyeh",
    pos:        "noun",
    definition: ["husk, peel, skin of some animals"],
    tags:       ["advanced", "nature", "animals"],
    examples:   [],
  },
  {
    word:       "arnerre",
    phonetic:   "arn-ERR-eh",
    pos:        "noun",
    definition: ["rockhole (where water collects)"],
    tags:       ["advanced", "nature", "country"],
    examples:   [],
  },
  {
    word:       "urlpe",
    phonetic:   "OOrl-beh",
    pos:        "noun",
    definition: ["red ochre"],
    tags:       ["advanced", "nature", "culture"],
    examples:   [],
  },
  {
    word:       "ankere",
    phonetic:   "ung-GERR-eh",
    pos:        "noun",
    definition: ["spinifex resin"],
    tags:       ["advanced", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "Atyewe",
    phonetic:   "uh-CHEH-weh",
    pos:        "noun",
    definition: ["Friend"],
    tags:       ["beginner"],
    examples:   ["Angwenhe atyewe ngkwenhe? (Who is your friend?)"],
  },
  {
    word:       "Angwenhe",
    phonetic:   "ang-wan-ha",
    pos:        "interrogative",
    definition: ["Who, which person?"],
    tags:       ["beginner"],
    examples:   ["Angwenhe unte? (Who are you?)", "Angwenhe atyewe ngkwenhe? (Who is your friend?)"],
  },
  {
    word:       "Arrangkwe",
    phonetic:   "a-rang-kwa",
    pos:        "interjection",
    definition: ["no, nothing, none", "A negative response"],
    tags:       ["beginner"],
    examples:   ["Arrangkwe, ayenge arratye-apetyeke. (No, I'm not coming back.)"],
  },
  {
    word:       "Atyenhe",
    phonetic:   "uh-CHEN-eh",
    pos:        "determiner",
    definition: ["my, mine"],
    tags:       ["beginner"],
    examples:   ["Arritnye atyenhe ... (My name is ...)"],
  },
  {
    word:       "Inwenhe",
    phonetic:   "In-wen-ha",
    pos:        "interrogative",
    definition: ["what?"],
    tags:       ["beginner"],
    examples:   ["Inwenhe arlte lyete? (What is the day today?)", "Inwenhe arritnye ngkwenhe? (What is your name?)"],
  },
  {
    word:       "Arritnye",
    phonetic:   "uh-REET-nya",
    pos:        "noun",
    definition: ["Name"],
    tags:       ["beginner"],
    examples:   ["Inwenhe arritnye ngkwenhe? (What is your name?)", "Arritnye atyenhe ... (My name is ...)"],
  },
  {
    word:       "Mwerre",
    phonetic:   "mwa-rra",
    pos:        "adjective",
    definition: ["good, well, useable, proper, safe", "Nice, pleasant, welcome, enjoyable", "Useable, in working order, OK"],
    tags:       ["beginner"],
    examples:   ["Unte mwerre? (You good?)", "Ye, ayenge mwerre (Yes, I am good)"],
    notes:      "Also spelled Mwarre in some sources",
  },
  {
    word:       "Ye",
    phonetic:   "ya",
    pos:        "interjection",
    definition: ["Yes, Yeah", "May be an answer to a negative question"],
    tags:       ["beginner"],
    examples:   ["Ye, ayenge mwerre (Yes, I am good)"],
  },
  {
    word:       "Arelhe",
    phonetic:   "uh-REL-eh",
    pos:        "noun",
    definition: ["woman; Aboriginal person"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Artwe",
    phonetic:   "ART-weh",
    pos:        "noun",
    definition: ["man, initiated man"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Ampe",
    phonetic:   "UM-beh",
    pos:        "noun",
    definition: ["Child"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Yanhe",
    phonetic:   "YUN-eh",
    pos:        "demonstrative",
    definition: ["over there, that (mid distance)"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Nhenhe",
    phonetic:   "NEN-eh",
    pos:        "demonstrative",
    definition: ["here, this (close by)"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Nhakwe",
    phonetic:   "NA-gweh",
    pos:        "demonstrative",
    definition: ["that, there (distant)"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Arlenge",
    phonetic:   "AL-eng-eh",
    pos:        "adverb",
    definition: ["long way, distant"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Aneme",
    phonetic:   "UN-em-eh",
    pos:        "verb",
    definition: ["sit, live, be"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Tneme",
    phonetic:   "DNEM-eh",
    pos:        "verb",
    definition: ["to stand, be"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Inteme",
    phonetic:   "IN-dem-eh",
    pos:        "verb",
    definition: ["lie, lie down"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Arne",
    phonetic:   "ARN-eh",
    pos:        "noun",
    definition: ["tree, bush, stick, wood, thing"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Antyeme",
    phonetic:   "UN-chem-eh",
    pos:        "noun",
    definition: ["Bed"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "Ahelhe",
    phonetic:   "uh-HEL-eh",
    pos:        "noun",
    definition: ["ground, land, earth"],
    tags:       ["beginner"],
    examples:   [],
  },
  {
    word:       "aherre",
    phonetic:   "uh-HERR-eh",
    pos:        "noun",
    definition: ["red kangaroo"],
    tags:       ["beginner", "animals"],
    examples:   [],
  },
  {
    word:       "akngwelye",
    phonetic:   "ug-NGWEL-yeh",
    pos:        "noun",
    definition: ["dog"],
    tags:       ["beginner", "animals"],
    examples:   [],
  },
  {
    word:       "thipe",
    phonetic:   "DIB-eh",
    pos:        "noun",
    definition: ["bird"],
    tags:       ["beginner", "animals"],
    examples:   [],
  },
  {
    word:       "inarlenge",
    phonetic:   "in-ARL-eng-eh",
    pos:        "noun",
    definition: ["echidna, spiny anteater"],
    tags:       ["beginner", "animals"],
    examples:   [],
    notes:      "Inarlenge — character in Apmwe-kenhe Arne story",
  },
  {
    word:       "arrakerte",
    phonetic:   "uh-RRAK-ert-eh",
    pos:        "noun",
    definition: ["mouth"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "iltye",
    phonetic:   "IL-cheh",
    pos:        "noun",
    definition: ["hand, fingers"],
    tags:       ["beginner", "body"],
    examples:   ["Anwerne iltye atwelheme"],
  },
  {
    word:       "akaperte",
    phonetic:   "uh-gub-ERT-eh",
    pos:        "noun",
    definition: ["head"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "alhe",
    phonetic:   "AL-eh",
    pos:        "noun",
    definition: ["nose"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "alknge",
    phonetic:   "ULK-ngeh",
    pos:        "noun",
    definition: ["eye"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "ampere",
    phonetic:   "um-BER-eh",
    pos:        "noun",
    definition: ["knee"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "ingke",
    phonetic:   "ING-geh",
    pos:        "noun",
    definition: ["foot, toe"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "irlpe",
    phonetic:   "IRL-beh",
    pos:        "noun",
    definition: ["ear"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "pwerlepe",
    phonetic:   "bwERL-eb-eh",
    pos:        "noun",
    definition: ["shoulder"],
    tags:       ["beginner", "body"],
    examples:   [],
  },
  {
    word:       "utyewe",
    phonetic:   "ooch-EW-eh",
    pos:        "adjective",
    definition: ["skinny, thin"],
    tags:       ["beginner", "body", "describing"],
    examples:   [],
  },
  {
    word:       "Merne arlkwetye-ke anteme",
    phonetic:   "MERN-eh arl-GWED-yeh-geh UN-dem-eh",
    pos:        "phrase",
    definition: ["Time for morning tea / Let's have morning tea"],
    tags:       ["beginner", "classroom"],
    examples:   ["Merne arlkwetye-ke anteme (10:30–11:00)"],
  },
  {
    word:       "apetyaye!",
    phonetic:   "ub-ETCH-eye-eh",
    pos:        "phrase",
    definition: ["come here!"],
    tags:       ["beginner", "classroom", "command"],
    examples:   [],
  },
  {
    word:       "awethe angkaye",
    phonetic:   "uh-WED-eh ung-GEY-eh",
    pos:        "phrase",
    definition: ["say it again"],
    tags:       ["beginner", "classroom", "command"],
    examples:   [],
  },
  {
    word:       "irnterre angkaye",
    phonetic:   "irn-DERR-eh ung-GEY-eh",
    pos:        "phrase",
    definition: ["say it louder"],
    tags:       ["beginner", "classroom", "command"],
    examples:   ["Irnterre angkaye (say it louder)"],
  },
  {
    word:       "mwantye angkaye",
    phonetic:   "MWUN-cheh ung-GEY-eh",
    pos:        "phrase",
    definition: ["say it slower"],
    tags:       ["beginner", "classroom", "command"],
    examples:   ["Mwantye angkaye (say it slower)"],
  },
  {
    word:       "Akeme-irremele tnaye!",
    phonetic:   "ug-EM-eh ir-REM-eh-leh DNEY-eh",
    pos:        "phrase",
    definition: ["Stand up!"],
    tags:       ["beginner", "classroom", "command"],
    examples:   [],
  },
  {
    word:       "Arrerne-alhaye!",
    phonetic:   "uh-RERN-eh ul-HEY-eh",
    pos:        "phrase",
    definition: ["Sit down!"],
    tags:       ["beginner", "classroom", "command"],
    examples:   [],
  },
  {
    word:       "Angkentye awaye!",
    phonetic:   "ung-GEN-cheh uh-WEY-eh",
    pos:        "phrase",
    definition: ["Listen to the word!"],
    tags:       ["beginner", "classroom", "command"],
    examples:   [],
  },
  {
    word:       "Angkentye awethe angkaye!",
    phonetic:   "ung-GEN-cheh uh-WED-eh ung-GEY-eh",
    pos:        "phrase",
    definition: ["Repeat the word!"],
    tags:       ["beginner", "classroom", "command"],
    examples:   [],
  },
  {
    word:       "irnterre",
    phonetic:   "irn-DERR-eh",
    pos:        "adverb",
    definition: ["intensely, energetically, loudly"],
    tags:       ["beginner", "classroom", "describing"],
    examples:   ["Irnterre angkaye (say it louder)"],
  },
  {
    word:       "nthakene unte angkeme",
    phonetic:   "NDAK-en-eh OON-deh ung-GEM-eh",
    pos:        "phrase",
    definition: ["how do you say ___?"],
    tags:       ["beginner", "classroom", "interaction"],
    examples:   ["Nthakene unte angkeme ___? (how do you say ___?)"],
  },
  {
    word:       "angkentye",
    phonetic:   "ung-GEN-cheh",
    pos:        "noun",
    definition: ["language, message"],
    tags:       ["beginner", "communication", "culture"],
    examples:   [],
  },
  {
    word:       "tantyape",
    phonetic:   "dun-CHUB-eh",
    pos:        "noun",
    definition: ["town"],
    tags:       ["beginner", "country"],
    examples:   ["Tantyape-werne (to town)"],
  },
  {
    word:       "Mparntwe",
    phonetic:   "m'barn-twa",
    pos:        "noun",
    definition: ["The Alice Springs town area"],
    tags:       ["beginner", "country"],
    examples:   [],
  },
  {
    word:       "Apmere",
    phonetic:   "Ap-mara",
    pos:        "noun",
    definition: ["Country, land, region", "Place, location, site, spot", "Camp, home, house"],
    tags:       ["beginner", "country"],
    examples:   [],
  },
  {
    word:       "akurne",
    phonetic:   "ug-ORN-eh",
    pos:        "adjective",
    definition: ["bad, wrong, not useable"],
    tags:       ["beginner", "describing"],
    examples:   [],
  },
  {
    word:       "anthurre",
    phonetic:   "un-DHORR-eh",
    pos:        "adverb",
    definition: ["very, really"],
    tags:       ["beginner", "describing"],
    examples:   [],
  },
  {
    word:       "apeke",
    phonetic:   "ub-EK-eh",
    pos:        "adverb",
    definition: ["perhaps, maybe"],
    tags:       ["beginner", "describing"],
    examples:   [],
  },
  {
    word:       "arlpentye",
    phonetic:   "arl-BEN-cheh",
    pos:        "adjective",
    definition: ["tall, long"],
    tags:       ["beginner", "describing"],
    examples:   [],
  },
  {
    word:       "mwantye",
    phonetic:   "MWUN-cheh",
    pos:        "adverb",
    definition: ["slowly, carefully, cautiously"],
    tags:       ["beginner", "describing"],
    examples:   [],
  },
  {
    word:       "arratye",
    phonetic:   "uh-RUCH-eh",
    pos:        "adjective",
    definition: ["true, right, real, straight"],
    tags:       ["beginner", "describing"],
    examples:   [],
  },
  {
    word:       "Ayekaye!",
    phonetic:   "eye-eh-KAY-eh",
    pos:        "interjection",
    definition: ["'Oh!', 'Oh no!', 'Wow.'"],
    tags:       ["beginner", "emotion"],
    examples:   [],
  },
  {
    word:       "Yekwe",
    phonetic:   "YEK-weh",
    pos:        "interjection",
    definition: ["'Dunno.', 'I don't know'"],
    tags:       ["beginner", "emotion"],
    examples:   [],
  },
  {
    word:       "alhwarre",
    phonetic:   "ul-HWARR-eh",
    pos:        "adjective",
    definition: ["sad, feeling sorrow"],
    tags:       ["beginner", "emotion"],
    examples:   [],
  },
  {
    word:       "akunye",
    phonetic:   "ug-OON-yeh",
    pos:        "interjection",
    definition: ["poor thing, dear thing", "expression of sympathy"],
    tags:       ["beginner", "emotion", "interaction"],
    examples:   [],
  },
  {
    word:       "kere",
    phonetic:   "GERR-eh",
    pos:        "noun",
    definition: ["meat, game animal"],
    tags:       ["beginner", "food", "animals"],
    examples:   [],
  },
  {
    word:       "Ngkwenhe",
    phonetic:   "ngGWEN-eh",
    pos:        "determiner",
    definition: ["Your (possessive)"],
    tags:       ["beginner", "grammar"],
    examples:   ["Iwenhe arritnye ngkwenhe? (What is your name?)"],
  },
  {
    word:       "iwenheke",
    phonetic:   "IW-en-hek-eh",
    pos:        "interrogative",
    definition: ["why?, what for?"],
    tags:       ["beginner", "grammar"],
    examples:   [],
  },
  {
    word:       "nthakenhe",
    phonetic:   "NDAK-en-eh",
    pos:        "interrogative",
    definition: ["how?"],
    tags:       ["beginner", "grammar"],
    examples:   [],
  },
  {
    word:       "atyinhe",
    phonetic:   "uh-CHIN-eh",
    pos:        "determiner",
    definition: ["my, mine"],
    tags:       ["beginner", "grammar"],
    examples:   [],
    notes:      "Alternate form of atyenhe",
  },
  {
    word:       "Mwerre anthurre",
    phonetic:   "MWER-reh un-DHORR-eh",
    pos:        "phrase",
    definition: ["Very good / Excellent"],
    tags:       ["beginner", "interaction"],
    examples:   ["Apmere nhenhe mwerre anthurre (This place is very good)"],
  },
  {
    word:       "ayenge alkngwirreme",
    phonetic:   "eye-ENG-eh ulk-NGWIR-rem-eh",
    pos:        "phrase",
    definition: ["I forgot"],
    tags:       ["beginner", "interaction"],
    examples:   ["Ayenge alkngwirre-ke (I forgot)"],
  },
  {
    word:       "kele the aweme",
    phonetic:   "GEL-eh deh uh-WEM-eh",
    pos:        "phrase",
    definition: ["I understand"],
    tags:       ["beginner", "interaction"],
    examples:   ["Kele, the aweme (I understand)"],
  },
  {
    word:       "mpe!",
    phonetic:   "mbeh",
    pos:        "interjection",
    definition: ["let's go!"],
    tags:       ["beginner", "interaction"],
    examples:   ["Mpe! Alhetyeke (Come on! Let's go)"],
  },
  {
    word:       "Urreke",
    phonetic:   "oo-ree-ga",
    pos:        "interjection",
    definition: ["goodbye, farewell; later, in a while"],
    tags:       ["beginner", "interaction"],
    examples:   ["Urreke! Nhenhe apetyeke. (Goodbye! See you later.)"],
    notes:      "Site defines as 'later, in a while, after' — also used as farewell",
  },
  {
    word:       "uyarne",
    phonetic:   "oo-YARN-eh",
    pos:        "adverb",
    definition: ["trying but unable to, unsuccessfully"],
    tags:       ["beginner", "interaction"],
    examples:   ["Uyarne the aweme (I don't understand)"],
  },
  {
    word:       "uyarne the aweme",
    phonetic:   "oo-YARN-eh deh uh-WEM-eh",
    pos:        "phrase",
    definition: ["I don't understand"],
    tags:       ["beginner", "interaction"],
    examples:   ["Uyarne the aweme (I don't understand)"],
  },
  {
    word:       "Ware",
    phonetic:   "WAR-eh",
    pos:        "interjection",
    definition: ["just, only; nothing much (answer to 'Werte?')"],
    tags:       ["beginner", "interaction"],
    examples:   ["Werte? — Ware (What's up? — Not much)"],
  },
  {
    word:       "Werte",
    phonetic:   "wer-da",
    pos:        "interjection",
    definition: ["'What's up?' 'What's going on?'"],
    tags:       ["beginner", "interaction"],
    examples:   ["Werte? — Ware (What's up? — Not much)"],
  },
  {
    word:       "kele",
    phonetic:   "GEL-eh",
    pos:        "interjection",
    definition: ["'Done!', 'OK', finished, already"],
    tags:       ["beginner", "interaction"],
    examples:   [],
  },
  {
    word:       "arrkene",
    phonetic:   "uh-RGEN-eh",
    pos:        "noun",
    definition: ["fun, play, joking"],
    tags:       ["beginner", "interaction"],
    examples:   [],
  },
  {
    word:       "nthenhe-werne",
    phonetic:   "NDEN-eh WERN-eh",
    pos:        "interrogative",
    definition: ["where to?"],
    tags:       ["beginner", "location", "grammar"],
    examples:   [],
  },
  {
    word:       "Apwerte",
    phonetic:   "ub-WERT-eh",
    pos:        "noun",
    definition: ["rock, stone, hill, money"],
    tags:       ["beginner", "nature"],
    examples:   [],
    notes:      "Consonant pronounced with rounded lips (w-form)",
  },
  {
    word:       "ure",
    phonetic:   "OR-eh",
    pos:        "noun",
    definition: ["fire"],
    tags:       ["beginner", "nature"],
    examples:   [],
  },
  {
    word:       "mutekaye",
    phonetic:   "mood-eg-EY-eh",
    pos:        "noun",
    definition: ["car"],
    tags:       ["beginner", "objects"],
    examples:   ["Unte mutekaye-kwenye? (You don't have a car?)"],
  },
  {
    word:       "Ayenge",
    phonetic:   "eye-ENG-eh",
    pos:        "pronoun",
    definition: ["I (1st person singular)"],
    tags:       ["beginner", "pronoun"],
    examples:   ["Ayenge mwerre (I am good)", "Arritnye atyenhe ... (My name is ...)"],
  },
  {
    word:       "Unte",
    phonetic:   "OON-deh",
    pos:        "pronoun",
    definition: ["You (2nd person singular)"],
    tags:       ["beginner", "pronoun"],
    examples:   ["Unte mwerre? (You good?)", "Unte nthenhe-arenye? (Where are you from?)"],
  },
  {
    word:       "Re",
    phonetic:   "reh",
    pos:        "pronoun",
    definition: ["He / She / It (3rd person singular)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "Ilerne",
    phonetic:   "il-ERN-eh",
    pos:        "pronoun",
    definition: ["We two (1st person dual)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "Mpwele",
    phonetic:   "mbWEL-eh",
    pos:        "pronoun",
    definition: ["You two (2nd person dual)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "Re-atherre",
    phonetic:   "reh uh-DERR-eh",
    pos:        "pronoun",
    definition: ["the two of them, they (subject)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "Anwerne",
    phonetic:   "un-WERN-eh",
    pos:        "pronoun",
    definition: ["we (more than two people; subject)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "Arrantherre",
    phonetic:   "uh-RUN-derr-eh",
    pos:        "pronoun",
    definition: ["you (more than two people; subject)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "Itne",
    phonetic:   "IT-neh",
    pos:        "pronoun",
    definition: ["they (more than two; subject)"],
    tags:       ["beginner", "pronoun"],
    examples:   [],
  },
  {
    word:       "ngkwinhe",
    phonetic:   "ngGWIN-eh",
    pos:        "pronoun",
    definition: ["your (possessive 2nd person singular)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Ampe ngkwinhe atherre (your two children)"],
  },
  {
    word:       "anwernekenhe",
    phonetic:   "un-WERN-eh-gen-eh",
    pos:        "pronoun",
    definition: ["our (possessive 1st person plural)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Apmere anwerne-kenhe (our home)"],
  },
  {
    word:       "itneke",
    phonetic:   "IT-neh-geh",
    pos:        "pronoun",
    definition: ["for them (dative 3rd person plural)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Ayeye itne-ke ileke (told them the story)"],
  },
  {
    word:       "ikwere",
    phonetic:   "ig-WER-eh",
    pos:        "pronoun",
    definition: ["for him/her/it (dative 3rd person singular)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Ikwere the merne iteke (cooked food for him/her)"],
  },
  {
    word:       "itnekenhe",
    phonetic:   "IT-neh-gen-eh",
    pos:        "pronoun",
    definition: ["theirs (possessive 3rd person plural)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Kere arlewatyerre itnekenhe (their goanna meat)"],
  },
  {
    word:       "atyenge",
    phonetic:   "uh-CHENG-eh",
    pos:        "pronoun",
    definition: ["for me (dative 1st person singular)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Kwatye atyenge inaye! (Get water for me!)"],
  },
  {
    word:       "ikwerenhe",
    phonetic:   "ig-WER-en-eh",
    pos:        "pronoun",
    definition: ["his/her/its (possessive 3rd person singular)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Merne ikwerenhe (his/her food)"],
  },
  {
    word:       "ngkwenge",
    phonetic:   "ngGWENG-eh",
    pos:        "pronoun",
    definition: ["for you (dative 2nd person singular)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["Ngkwenge re apay-uthneme-ke (he/she asked for you)"],
  },
  {
    word:       "the",
    phonetic:   "deh",
    pos:        "pronoun",
    definition: ["I (subject of transitive verb)"],
    tags:       ["beginner", "pronoun", "grammar"],
    examples:   ["The merne iteme (I am cooking the food)"],
    notes:      "Used as subject of transitive verbs; ayenge used for intransitive verbs",
  },
  {
    word:       "akngerre",
    phonetic:   "ug-NGERR-eh",
    pos:        "adjective",
    definition: ["big, much, a lot"],
    tags:       ["beginner", "quantity"],
    examples:   [],
  },
  {
    word:       "akweke",
    phonetic:   "ug-WEK-eh",
    pos:        "adjective",
    definition: ["small, little, not much"],
    tags:       ["beginner", "quantity"],
    examples:   [],
  },
  {
    word:       "Arlte",
    phonetic:   "ARL-deh",
    pos:        "noun",
    definition: ["day, daylight"],
    tags:       ["beginner", "time"],
    examples:   ["Inwenhe arlte lyete? (What is the day today?)"],
  },
  {
    word:       "Lyete",
    phonetic:   "LYEH-deh",
    pos:        "noun",
    definition: ["yesterday"],
    tags:       ["beginner", "time"],
    examples:   ["Iwenhe apmwerrke aneke (Yesterday was ...)"],
  },
  {
    word:       "Apmwerrke",
    phonetic:   "ub-MWERK-eh",
    pos:        "noun",
    definition: ["tomorrow"],
    tags:       ["beginner", "time"],
    examples:   [],
    notes:      "Site lists as 'yesterday' — slides use apmwerrke = tomorrow; check with language advisor",
  },
  {
    word:       "Ingwenthe",
    phonetic:   "ing-WEN-deh",
    pos:        "noun",
    definition: ["The day after tomorrow / future time"],
    tags:       ["beginner", "time"],
    examples:   [],
  },
  {
    word:       "akwete",
    phonetic:   "ug-WED-eh",
    pos:        "adverb",
    definition: ["still, yet, continuing"],
    tags:       ["beginner", "time"],
    examples:   [],
  },
  {
    word:       "anteme",
    phonetic:   "UN-dem-eh",
    pos:        "adverb",
    definition: ["now, then"],
    tags:       ["beginner", "time"],
    examples:   [],
  },
  {
    word:       "ilengare",
    phonetic:   "il-eng-AR-eh",
    pos:        "interrogative",
    definition: ["when?"],
    tags:       ["beginner", "time", "grammar"],
    examples:   [],
  },
  {
    word:       "alkngwirreme",
    phonetic:   "ulk-NGWIR-rem-eh",
    pos:        "verb",
    definition: ["forget"],
    tags:       ["beginner", "verb"],
    examples:   ["Ayenge alkngwirre-ke (I forgot)"],
  },
  {
    word:       "Urrkepeme",
    phonetic:   "oor-KEB-em-eh",
    pos:        "verb",
    definition: ["Work"],
    tags:       ["beginner", "verb"],
    examples:   ["Unte nthenhe-le urrkepeme? (Where do you work?)", "Ayenge (workplace)-le urrkepeme (I work at ...)"],
  },
  {
    word:       "Alkweme-le",
    phonetic:   "al-GWEM-eh-leh",
    pos:        "verb",
    definition: ["Eat"],
    tags:       ["beginner", "verb"],
    examples:   [],
  },
  {
    word:       "Iteme",
    phonetic:   "ID-em-eh",
    pos:        "verb",
    definition: ["cook, light (a fire)"],
    tags:       ["beginner", "verb"],
    examples:   [],
  },
  {
    word:       "Antyweme",
    phonetic:   "un-CHWEM-eh",
    pos:        "verb",
    definition: ["drink something"],
    tags:       ["beginner", "verb"],
    examples:   [],
  },
  {
    word:       "Atweme",
    phonetic:   "ut-WEM-eh",
    pos:        "verb",
    definition: ["hit, kill"],
    tags:       ["beginner", "verb"],
    examples:   [],
    notes:      "Consonant pronounced with rounded lips (w-form)",
  },
  {
    word:       "arlkweme",
    phonetic:   "arl-GWEM-eh",
    pos:        "verb",
    definition: ["eat; ache"],
    tags:       ["beginner", "verb"],
    examples:   [],
  },
  {
    word:       "angkeme",
    phonetic:   "ung-GEM-eh",
    pos:        "verb",
    definition: ["speak, talk"],
    tags:       ["beginner", "verb", "communication"],
    examples:   [],
  },
  {
    word:       "aweme",
    phonetic:   "uh-WEM-eh",
    pos:        "verb",
    definition: ["hear, listen to, understand"],
    tags:       ["beginner", "verb", "communication"],
    examples:   [],
  },
  {
    word:       "Aneke",
    phonetic:   "UN-ek-eh",
    pos:        "verb",
    definition: ["Was (past tense of aneme)"],
    tags:       ["beginner", "verb", "grammar"],
    examples:   ["Iwenhe apmwerrke aneke (Yesterday was ...)"],
    notes:      "Past tense form of aneme (is)",
  },
  {
    word:       "Anetyenhe",
    phonetic:   "un-eh-CHEN-eh",
    pos:        "verb",
    definition: ["Will be (future tense of aneme)"],
    tags:       ["beginner", "verb", "grammar"],
    examples:   [],
    notes:      "Future tense form of aneme (is)",
  },
  {
    word:       "alheme",
    phonetic:   "ul-HEM-eh",
    pos:        "verb",
    definition: ["go, go along, travel"],
    tags:       ["beginner", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "apetyeme",
    phonetic:   "ub-ETCH-em-eh",
    pos:        "verb",
    definition: ["come"],
    tags:       ["beginner", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "itelareme",
    phonetic:   "id-el-UR-em-eh",
    pos:        "verb",
    definition: ["remember, know, decide, think"],
    tags:       ["beginner", "verb", "thinking"],
    examples:   [],
  },
  {
    word:       "itirreme",
    phonetic:   "id-IR-rem-eh",
    pos:        "verb",
    definition: ["think"],
    tags:       ["beginner", "verb", "thinking"],
    examples:   [],
  },
  {
    word:       "Kwatye",
    phonetic:   "kwa-dja",
    pos:        "noun",
    definition: ["water, rain", "Rain", "Ice, vapour, rain clouds"],
    tags:       ["beginner", "weather"],
    examples:   ["Thipe nyingkele apele kwatye imerntye akngerre..."],
  },
  {
    word:       "apmwe",
    phonetic:   "UB-mweh",
    pos:        "noun",
    definition: ["snake"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "arlewatyerre",
    phonetic:   "arl-eh-WUCH-err-eh",
    pos:        "noun",
    definition: ["sand goanna"],
    tags:       ["intermediate", "animals"],
    examples:   ["Kere arlewatyerre itnekenhe (their goanna meat)"],
  },
  {
    word:       "aherte",
    phonetic:   "uh-HERT-eh",
    pos:        "noun",
    definition: ["bilby, rabbit-eared bandicoot"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "angeme",
    phonetic:   "ung-EM-eh",
    pos:        "noun",
    definition: ["fly (insect)"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "ankerte",
    phonetic:   "ung-GERT-eh",
    pos:        "noun",
    definition: ["bearded dragon (lizard)"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "antenhe",
    phonetic:   "un-DEN-eh",
    pos:        "noun",
    definition: ["possum"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "apwelantye",
    phonetic:   "ub-wel-UN-cheh",
    pos:        "noun",
    definition: ["black kite (bird)"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "arenge",
    phonetic:   "uh-RENG-eh",
    pos:        "noun",
    definition: ["euro (kangaroo)"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "arleye",
    phonetic:   "uh-RLEY-eh",
    pos:        "noun",
    definition: ["emu"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "arrwe",
    phonetic:   "uh-RWEH",
    pos:        "noun",
    definition: ["rock wallaby"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "atnunthe",
    phonetic:   "ud-NOON-deh",
    pos:        "noun",
    definition: ["animal"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "atwetye",
    phonetic:   "ut-WED-yeh",
    pos:        "noun",
    definition: ["joey"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "irrarnte",
    phonetic:   "ir-RARN-deh",
    pos:        "noun",
    definition: ["black cockatoo"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "irretye",
    phonetic:   "ir-RECH-eh",
    pos:        "noun",
    definition: ["wedge-tailed eagle"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "nanthe",
    phonetic:   "NUN-deh",
    pos:        "noun",
    definition: ["horse"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "unyerre",
    phonetic:   "oon-YERR-eh",
    pos:        "noun",
    definition: ["thorny devil (lizard)"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "yepe-yepe",
    phonetic:   "YEP-eh YEP-eh",
    pos:        "noun",
    definition: ["sheep"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "yerre",
    phonetic:   "YERR-eh",
    pos:        "noun",
    definition: ["ant"],
    tags:       ["intermediate", "animals"],
    examples:   [],
  },
  {
    word:       "yerrampe",
    phonetic:   "YERR-um-beh",
    pos:        "noun",
    definition: ["honey-ant"],
    tags:       ["intermediate", "animals", "food"],
    examples:   [],
  },
  {
    word:       "ahentye",
    phonetic:   "uh-HEN-cheh",
    pos:        "noun",
    definition: ["throat"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "aleme",
    phonetic:   "ul-EM-eh",
    pos:        "noun",
    definition: ["liver"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "alhwe",
    phonetic:   "UL-hweh",
    pos:        "noun",
    definition: ["blood"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "alte",
    phonetic:   "UL-deh",
    pos:        "noun",
    definition: ["hair, fur"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "amake",
    phonetic:   "um-AK-eh",
    pos:        "noun",
    definition: ["elbow"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "amulte",
    phonetic:   "um-OOL-deh",
    pos:        "noun",
    definition: ["arm"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "artepe",
    phonetic:   "art-EB-eh",
    pos:        "noun",
    definition: ["back (body part)"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "artitye",
    phonetic:   "art-ID-yeh",
    pos:        "noun",
    definition: ["teeth"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "atnerte",
    phonetic:   "ud-NERT-eh",
    pos:        "noun",
    definition: ["stomach"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "ite",
    phonetic:   "ID-eh",
    pos:        "noun",
    definition: ["throat, front of neck"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "pelhe",
    phonetic:   "PEL-eh",
    pos:        "noun",
    definition: ["saliva, spit"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "ulyepere",
    phonetic:   "ool-yeb-ER-eh",
    pos:        "noun",
    definition: ["thigh"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "untye",
    phonetic:   "OON-cheh",
    pos:        "noun",
    definition: ["back of neck, neck"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "urle",
    phonetic:   "OOR-leh",
    pos:        "noun",
    definition: ["forehead"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "utyene",
    phonetic:   "ooch-EN-eh",
    pos:        "noun",
    definition: ["sore (on body), wound"],
    tags:       ["intermediate", "body"],
    examples:   [],
  },
  {
    word:       "tyerrtye",
    phonetic:   "CHERR-cheh",
    pos:        "noun",
    definition: ["(person's) body; Aboriginal person"],
    tags:       ["intermediate", "body", "people"],
    examples:   [],
  },
  {
    word:       "angayakwe",
    phonetic:   "ung-eye-YUK-weh",
    pos:        "adjective",
    definition: ["hungry"],
    tags:       ["intermediate", "body", "states"],
    examples:   [],
  },
  {
    word:       "angkethakwe",
    phonetic:   "ung-ged-UK-weh",
    pos:        "adjective",
    definition: ["thirsty"],
    tags:       ["intermediate", "body", "states"],
    examples:   [],
  },
  {
    word:       "apurrke",
    phonetic:   "ub-ORK-eh",
    pos:        "adjective",
    definition: ["tired"],
    tags:       ["intermediate", "body", "states"],
    examples:   [],
  },
  {
    word:       "atnerte-atnerte",
    phonetic:   "ud-NERT-eh ud-NERT-eh",
    pos:        "adjective",
    definition: ["pregnant"],
    tags:       ["intermediate", "body", "states"],
    examples:   [],
  },
  {
    word:       "rlkerte",
    phonetic:   "rlGERT-eh",
    pos:        "adjective",
    definition: ["sick"],
    tags:       ["intermediate", "body", "states"],
    examples:   [],
  },
  {
    word:       "aheye-angkeme",
    phonetic:   "uh-HEY-eh ung-GEM-eh",
    pos:        "verb",
    definition: ["to breathe"],
    tags:       ["intermediate", "body", "verb"],
    examples:   [],
  },
  {
    word:       "athetheke",
    phonetic:   "ud-ed-EK-eh",
    pos:        "adjective",
    definition: ["red and some shades of pink and orange"],
    tags:       ["intermediate", "colour"],
    examples:   [],
  },
  {
    word:       "mperlkere",
    phonetic:   "mberl-GERR-eh",
    pos:        "adjective",
    definition: ["white"],
    tags:       ["intermediate", "colour"],
    examples:   [],
  },
  {
    word:       "urrperle",
    phonetic:   "oor-BERL-eh",
    pos:        "adjective",
    definition: ["dark colours, especially black; Aboriginal person"],
    tags:       ["intermediate", "colour", "culture"],
    examples:   [],
  },
  {
    word:       "apele",
    phonetic:   "ub-EL-eh",
    pos:        "adverb",
    definition: ["'I know this myself', definitely"],
    tags:       ["intermediate", "communication"],
    examples:   [],
  },
  {
    word:       "ayeye",
    phonetic:   "eye-EY-eh",
    pos:        "noun",
    definition: ["story, message"],
    tags:       ["intermediate", "communication", "culture"],
    examples:   ["Ayeye itne-ke ileke (told them the story)"],
  },
  {
    word:       "iwerre",
    phonetic:   "IW-err-eh",
    pos:        "noun",
    definition: ["path, road, track"],
    tags:       ["intermediate", "country", "travel"],
    examples:   [],
  },
  {
    word:       "irntirte",
    phonetic:   "irn-DIRT-eh",
    pos:        "adjective",
    definition: ["rotten, bad, very bad"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "lyempenye",
    phonetic:   "LYEM-ben-yeh",
    pos:        "adjective",
    definition: ["grey-haired, old"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "artangentye",
    phonetic:   "art-ung-EN-cheh",
    pos:        "adverb",
    definition: ["together, co-operatively"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "iparrpe",
    phonetic:   "ib-ARR-beh",
    pos:        "adverb",
    definition: ["fast, quickly"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "lterrke",
    phonetic:   "LDERK-eh",
    pos:        "adjective",
    definition: ["hard, strong, solid, tight"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "nterte",
    phonetic:   "NDERT-eh",
    pos:        "adverb",
    definition: ["quiet, quietly"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "ulpe",
    phonetic:   "OOL-beh",
    pos:        "adjective",
    definition: ["fine, powdery, soft"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "ulthentye",
    phonetic:   "ool-DEN-cheh",
    pos:        "adjective",
    definition: ["heavy"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "alkarle",
    phonetic:   "ul-GAR-leh",
    pos:        "adjective",
    definition: ["new, flash"],
    tags:       ["intermediate", "describing"],
    examples:   [],
  },
  {
    word:       "arerte",
    phonetic:   "uh-RERT-eh",
    pos:        "adjective",
    definition: ["mad, crazy, silly; deaf"],
    tags:       ["intermediate", "describing", "states"],
    examples:   [],
  },
  {
    word:       "aternnge",
    phonetic:   "ud-ERN-ngeh",
    pos:        "adjective",
    definition: ["dirty"],
    tags:       ["intermediate", "describing", "states"],
    examples:   [],
  },
  {
    word:       "ahe, ahele",
    phonetic:   "AH-eh, uh-HEL-eh",
    pos:        "adverb",
    definition: ["in anger, angrily, fighting"],
    tags:       ["intermediate", "emotion"],
    examples:   [],
  },
  {
    word:       "ahe-akngerre",
    phonetic:   "AH-eh ug-NGERR-eh",
    pos:        "adjective",
    definition: ["aggressive, 'cheeky', angry"],
    tags:       ["intermediate", "emotion"],
    examples:   [],
  },
  {
    word:       "apure",
    phonetic:   "ub-OR-eh",
    pos:        "adjective",
    definition: ["shy, ashamed, embarrassed, reserved"],
    tags:       ["intermediate", "emotion", "states"],
    examples:   [],
  },
  {
    word:       "atere",
    phonetic:   "ud-ER-eh",
    pos:        "adjective",
    definition: ["scared, afraid, frightened"],
    tags:       ["intermediate", "emotion", "states"],
    examples:   [],
  },
  {
    word:       "atnerre",
    phonetic:   "ud-NERR-eh",
    pos:        "adjective",
    definition: ["brave, confident, not scared"],
    tags:       ["intermediate", "emotion", "states"],
    examples:   [],
  },
  {
    word:       "irrare",
    phonetic:   "ir-RAR-eh",
    pos:        "adjective",
    definition: ["lonely, homesick"],
    tags:       ["intermediate", "emotion", "states"],
    examples:   [],
  },
  {
    word:       "ahele-irreme",
    phonetic:   "uh-HEL-eh IR-rem-eh",
    pos:        "verb",
    definition: ["be angry, get aggressive"],
    tags:       ["intermediate", "emotion", "verb"],
    examples:   [],
  },
  {
    word:       "akangkeme",
    phonetic:   "uh-GUNG-gem-eh",
    pos:        "verb",
    definition: ["be happy, be pleased"],
    tags:       ["intermediate", "emotion", "verb"],
    examples:   [],
  },
  {
    word:       "akngeye",
    phonetic:   "ug-NGEY-eh",
    pos:        "noun",
    definition: ["father, father's brother"],
    tags:       ["intermediate", "family"],
    examples:   [],
  },
  {
    word:       "atyeye",
    phonetic:   "uh-CHEY-eh",
    pos:        "noun",
    definition: ["younger brother or sister"],
    tags:       ["intermediate", "family"],
    examples:   [],
  },
  {
    word:       "kake",
    phonetic:   "GAK-eh",
    pos:        "noun",
    definition: ["older brother"],
    tags:       ["intermediate", "family"],
    examples:   [],
  },
  {
    word:       "matye",
    phonetic:   "MUCH-eh",
    pos:        "noun",
    definition: ["mother, mother's sister"],
    tags:       ["intermediate", "family"],
    examples:   [],
  },
  {
    word:       "yaye",
    phonetic:   "YEY-eh",
    pos:        "noun",
    definition: ["older sister"],
    tags:       ["intermediate", "family"],
    examples:   [],
  },
  {
    word:       "angkwere",
    phonetic:   "ung-GWER-eh",
    pos:        "noun",
    definition: ["older sister"],
    tags:       ["intermediate", "family"],
    examples:   [],
  },
  {
    word:       "Kwarte",
    phonetic:   "KWART-eh",
    pos:        "noun",
    definition: ["Egg"],
    tags:       ["intermediate", "food"],
    examples:   [],
    notes:      "Consonant pronounced with rounded lips (w-form)",
  },
  {
    word:       "antere",
    phonetic:   "un-DER-eh",
    pos:        "noun",
    definition: ["fat, grease"],
    tags:       ["intermediate", "food"],
    examples:   [],
  },
  {
    word:       "ikwemeye",
    phonetic:   "ig-WEM-eye-eh",
    pos:        "adjective",
    definition: ["sweet"],
    tags:       ["intermediate", "food", "describing"],
    examples:   [],
  },
  {
    word:       "mpenge",
    phonetic:   "mbENG-eh",
    pos:        "adjective",
    definition: ["ripe, cooked"],
    tags:       ["intermediate", "food", "describing"],
    examples:   [],
  },
  {
    word:       "awele-awele",
    phonetic:   "uh-WEL-eh uh-WEL-eh",
    pos:        "noun",
    definition: ["bush tomato"],
    tags:       ["intermediate", "food", "plants"],
    examples:   ["Awele-awele iwenhe-artyeke? (What does the bush tomato taste like?)"],
  },
  {
    word:       "anatye",
    phonetic:   "un-UCH-eh",
    pos:        "noun",
    definition: ["bush potato, type of yam"],
    tags:       ["intermediate", "food", "plants"],
    examples:   [],
  },
  {
    word:       "annge",
    phonetic:   "UN-ngeh",
    pos:        "noun",
    definition: ["seed, fruit"],
    tags:       ["intermediate", "food", "plants"],
    examples:   [],
  },
  {
    word:       "atwakeye",
    phonetic:   "ut-wug-EY-eh",
    pos:        "noun",
    definition: ["wild orange"],
    tags:       ["intermediate", "food", "plants"],
    examples:   [],
  },
  {
    word:       "yalke",
    phonetic:   "YUL-geh",
    pos:        "noun",
    definition: ["wild onion"],
    tags:       ["intermediate", "food", "plants"],
    examples:   [],
  },
  {
    word:       "angwenhe-kenhe",
    phonetic:   "ung-WEN-eh GEN-eh",
    pos:        "interrogative",
    definition: ["whose?"],
    tags:       ["intermediate", "grammar"],
    examples:   [],
  },
  {
    word:       "nthakentye",
    phonetic:   "ndak-EN-cheh",
    pos:        "interrogative",
    definition: ["how many?, how much?"],
    tags:       ["intermediate", "grammar", "quantity"],
    examples:   [],
  },
  {
    word:       "kweye",
    phonetic:   "GWEY-eh",
    pos:        "interjection",
    definition: ["'Eh?', 'I'm surprised; can that be right?'", "surprise or seeking confirmation"],
    tags:       ["intermediate", "interaction"],
    examples:   ["Kweye?"],
  },
  {
    word:       "yewe-yewe",
    phonetic:   "YEW-eh YEW-eh",
    pos:        "interjection",
    definition: ["yes, OK"],
    tags:       ["intermediate", "interaction"],
    examples:   [],
  },
  {
    word:       "akertne",
    phonetic:   "ug-ERT-neh",
    pos:        "adverb",
    definition: ["up, on top"],
    tags:       ["intermediate", "location"],
    examples:   [],
  },
  {
    word:       "akethe",
    phonetic:   "ug-ED-eh",
    pos:        "noun",
    definition: ["outside, in the open, clearing, plain"],
    tags:       ["intermediate", "location"],
    examples:   [],
  },
  {
    word:       "kwene",
    phonetic:   "GWEN-eh",
    pos:        "adverb",
    definition: ["down, low, inside"],
    tags:       ["intermediate", "location"],
    examples:   [],
  },
  {
    word:       "mpepe",
    phonetic:   "mbEB-eh",
    pos:        "noun",
    definition: ["middle"],
    tags:       ["intermediate", "location", "describing"],
    examples:   [],
  },
  {
    word:       "nthenhe",
    phonetic:   "NDEN-eh",
    pos:        "interrogative",
    definition: ["where?"],
    tags:       ["intermediate", "location", "grammar"],
    examples:   [],
  },
  {
    word:       "alkngenthe",
    phonetic:   "ulk-NGEN-deh",
    pos:        "noun",
    definition: ["flame, light"],
    tags:       ["intermediate", "nature"],
    examples:   [],
  },
  {
    word:       "aperrke",
    phonetic:   "ub-ERK-eh",
    pos:        "noun",
    definition: ["hot coals"],
    tags:       ["intermediate", "nature"],
    examples:   [],
  },
  {
    word:       "atnyentye",
    phonetic:   "ud-NYEN-cheh",
    pos:        "noun",
    definition: ["moon"],
    tags:       ["intermediate", "nature"],
    examples:   [],
  },
  {
    word:       "ulye",
    phonetic:   "OOL-yeh",
    pos:        "noun",
    definition: ["shade, patchy or dappled shade"],
    tags:       ["intermediate", "nature"],
    examples:   [],
  },
  {
    word:       "inteye",
    phonetic:   "IN-dey-eh",
    pos:        "noun",
    definition: ["cave"],
    tags:       ["intermediate", "nature", "country"],
    examples:   [],
  },
  {
    word:       "alkere",
    phonetic:   "ul-KERR-eh",
    pos:        "noun",
    definition: ["sky"],
    tags:       ["intermediate", "nature", "country"],
    examples:   [],
  },
  {
    word:       "iperte",
    phonetic:   "ib-ERT-eh",
    pos:        "noun",
    definition: ["hole, pit, hollow, grave"],
    tags:       ["intermediate", "nature", "country"],
    examples:   [],
  },
  {
    word:       "lhere",
    phonetic:   "LHERR-eh",
    pos:        "noun",
    definition: ["creek, river"],
    tags:       ["intermediate", "nature", "country"],
    examples:   [],
  },
  {
    word:       "ankerre",
    phonetic:   "ung-GERR-eh",
    pos:        "noun",
    definition: ["coolibah tree"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "antethe",
    phonetic:   "un-DED-eh",
    pos:        "noun",
    definition: ["flower"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "arlpelhe",
    phonetic:   "arl-BEL-eh",
    pos:        "noun",
    definition: ["leaf, petal, feather, wing"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "artekerre",
    phonetic:   "art-eh-GERR-eh",
    pos:        "noun",
    definition: ["root"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "aywerte",
    phonetic:   "eye-WERT-eh",
    pos:        "noun",
    definition: ["spinifex"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "irrkepe",
    phonetic:   "irk-EB-eh",
    pos:        "noun",
    definition: ["desert oak"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "name",
    phonetic:   "NUM-eh",
    pos:        "noun",
    definition: ["grass"],
    tags:       ["intermediate", "nature", "plants"],
    examples:   [],
  },
  {
    word:       "atherrke",
    phonetic:   "ud-ERK-eh",
    pos:        "noun",
    definition: ["grass, small plants; green colour"],
    tags:       ["intermediate", "nature", "plants", "colour"],
    examples:   [],
  },
  {
    word:       "angkulye",
    phonetic:   "ung-GOO-lyeh",
    pos:        "noun",
    definition: ["cloud"],
    tags:       ["intermediate", "nature", "weather"],
    examples:   [],
  },
  {
    word:       "apwape",
    phonetic:   "ub-WAB-eh",
    pos:        "noun",
    definition: ["whirlwind, willy-willy"],
    tags:       ["intermediate", "nature", "weather"],
    examples:   [],
  },
  {
    word:       "apweteke",
    phonetic:   "ub-wed-EK-eh",
    pos:        "noun",
    definition: ["hailstones"],
    tags:       ["intermediate", "nature", "weather"],
    examples:   [],
  },
  {
    word:       "uterne",
    phonetic:   "ood-ERN-eh",
    pos:        "noun",
    definition: ["sun, summer"],
    tags:       ["intermediate", "nature", "weather"],
    examples:   [],
  },
  {
    word:       "irrtyurtne",
    phonetic:   "ir-CHORT-neh",
    pos:        "noun",
    definition: ["knife"],
    tags:       ["intermediate", "objects"],
    examples:   ["Arelhe-le irrtyurtne-le merne akeme (woman cuts food with a knife)"],
  },
  {
    word:       "pathekele",
    phonetic:   "bud-eg-EL-eh",
    pos:        "noun",
    definition: ["bicycle"],
    tags:       ["intermediate", "objects"],
    examples:   ["Unte pathekele-akerte? (Do you have a bicycle?)"],
  },
  {
    word:       "kwerte",
    phonetic:   "GWERT-eh",
    pos:        "noun",
    definition: ["smoke, cigarette"],
    tags:       ["intermediate", "objects"],
    examples:   [],
  },
  {
    word:       "mantere",
    phonetic:   "mun-DER-eh",
    pos:        "noun",
    definition: ["clothes, cloth"],
    tags:       ["intermediate", "objects"],
    examples:   [],
  },
  {
    word:       "warle",
    phonetic:   "WAR-leh",
    pos:        "noun",
    definition: ["house, building, wall"],
    tags:       ["intermediate", "objects", "country"],
    examples:   [],
  },
  {
    word:       "aywe",
    phonetic:   "EYE-weh",
    pos:        "noun",
    definition: ["older or middle-aged man"],
    tags:       ["intermediate", "people"],
    examples:   [],
  },
  {
    word:       "ampwe",
    phonetic:   "UM-bweh",
    pos:        "noun",
    definition: ["middle-aged or mature person"],
    tags:       ["intermediate", "people"],
    examples:   [],
  },
  {
    word:       "marle",
    phonetic:   "MAR-leh",
    pos:        "adjective",
    definition: ["female (girl, female animal)"],
    tags:       ["intermediate", "people", "animals"],
    examples:   [],
  },
  {
    word:       "ilernpenye",
    phonetic:   "il-ern-BEN-yeh",
    pos:        "noun",
    definition: ["expert, clever, skilled person"],
    tags:       ["intermediate", "people", "describing"],
    examples:   [],
  },
  {
    word:       "ampe marle",
    phonetic:   "UM-beh MAR-leh",
    pos:        "noun",
    definition: ["girl"],
    tags:       ["intermediate", "people", "family"],
    examples:   [],
  },
  {
    word:       "ampe urreye",
    phonetic:   "UM-beh oo-REE-yeh",
    pos:        "noun",
    definition: ["boy"],
    tags:       ["intermediate", "people", "family"],
    examples:   [],
  },
  {
    word:       "awenke",
    phonetic:   "uh-WENG-keh",
    pos:        "noun",
    definition: ["teenage girl, young woman"],
    tags:       ["intermediate", "people", "family"],
    examples:   [],
  },
  {
    word:       "ngenhe",
    phonetic:   "NGEN-eh",
    pos:        "pronoun",
    definition: ["you (one person; object form)"],
    tags:       ["intermediate", "pronoun", "grammar"],
    examples:   [],
  },
  {
    word:       "atherre",
    phonetic:   "ud-ERR-eh",
    pos:        "noun",
    definition: ["two, both, pair"],
    tags:       ["intermediate", "quantity"],
    examples:   [],
  },
  {
    word:       "urrpetye",
    phonetic:   "oor-BED-yeh",
    pos:        "noun",
    definition: ["three, a few"],
    tags:       ["intermediate", "quantity"],
    examples:   [],
  },
  {
    word:       "anyente",
    phonetic:   "un-YEN-deh",
    pos:        "noun",
    definition: ["one, alone"],
    tags:       ["intermediate", "quantity"],
    examples:   [],
  },
  {
    word:       "arunthe",
    phonetic:   "uh-ROON-deh",
    pos:        "adjective",
    definition: ["many, a lot, lots"],
    tags:       ["intermediate", "quantity"],
    examples:   [],
  },
  {
    word:       "akarre",
    phonetic:   "uh-GARR-eh",
    pos:        "adjective",
    definition: ["awake"],
    tags:       ["intermediate", "states"],
    examples:   [],
  },
  {
    word:       "ankwe",
    phonetic:   "UNG-gweh",
    pos:        "adjective",
    definition: ["asleep"],
    tags:       ["intermediate", "states"],
    examples:   [],
  },
  {
    word:       "itethe",
    phonetic:   "id-ED-eh",
    pos:        "adjective",
    definition: ["alive"],
    tags:       ["intermediate", "states"],
    examples:   [],
  },
  {
    word:       "akaltye",
    phonetic:   "ug-UL-cheh",
    pos:        "verb",
    definition: ["knowing how to, knowing about"],
    tags:       ["intermediate", "thinking", "culture"],
    examples:   [],
    notes:      "The name of this app — akaltye means 'knowing how to'",
  },
  {
    word:       "akwetethe",
    phonetic:   "ug-wed-ED-eh",
    pos:        "adverb",
    definition: ["always"],
    tags:       ["intermediate", "time"],
    examples:   [],
  },
  {
    word:       "angwerre",
    phonetic:   "ung-WERR-eh",
    pos:        "noun",
    definition: ["mid-afternoon"],
    tags:       ["intermediate", "time"],
    examples:   [],
  },
  {
    word:       "anngwerre-anngwerre",
    phonetic:   "ung-WERR-eh ung-WERR-eh",
    pos:        "noun",
    definition: ["late afternoon"],
    tags:       ["intermediate", "time"],
    examples:   [],
  },
  {
    word:       "arrule",
    phonetic:   "uh-ROOL-eh",
    pos:        "adverb",
    definition: ["long time ago, for a long time"],
    tags:       ["intermediate", "time"],
    examples:   [],
  },
  {
    word:       "ingweleme",
    phonetic:   "ing-WEL-em-eh",
    pos:        "noun",
    definition: ["morning"],
    tags:       ["intermediate", "time"],
    examples:   [],
  },
  {
    word:       "akeme-irreme",
    phonetic:   "ug-EM-eh IR-rem-eh",
    pos:        "verb",
    definition: ["get up"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "akngetyeme",
    phonetic:   "ug-NGECH-em-eh",
    pos:        "verb",
    definition: ["bring"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "alheweme",
    phonetic:   "ul-heh-WEM-eh",
    pos:        "verb",
    definition: ["wash something"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "ampeme",
    phonetic:   "um-BEM-eh",
    pos:        "verb",
    definition: ["burn"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "antheme",
    phonetic:   "un-DEM-eh",
    pos:        "verb",
    definition: ["give"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "areme",
    phonetic:   "uh-REM-eh",
    pos:        "verb",
    definition: ["see, look at, watch"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "atnyeneme",
    phonetic:   "ud-NYEN-em-eh",
    pos:        "verb",
    definition: ["hold, have, keep, look after"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "atwerreme",
    phonetic:   "ut-WERR-em-eh",
    pos:        "verb",
    definition: ["fight ('hit each other')"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "ineme",
    phonetic:   "IN-em-eh",
    pos:        "verb",
    definition: ["take, get"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "iweme",
    phonetic:   "IW-em-eh",
    pos:        "verb",
    definition: ["throw, throw away"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "marteme",
    phonetic:   "mart-EM-eh",
    pos:        "verb",
    definition: ["shut, close, block off, turn off"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "mpwareme",
    phonetic:   "mbWAR-em-eh",
    pos:        "verb",
    definition: ["make, do, fix"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "rakeme",
    phonetic:   "rug-EM-eh",
    pos:        "verb",
    definition: ["grab, snatch, take away"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "tnyeme",
    phonetic:   "DNYEM-eh",
    pos:        "verb",
    definition: ["dig for something, dig something out"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "uthneme",
    phonetic:   "OOD-nem-eh",
    pos:        "verb",
    definition: ["to bite"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "weme",
    phonetic:   "WEM-eh",
    pos:        "verb",
    definition: ["hit (by throwing something at)"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "akarelheme",
    phonetic:   "ug-ar-EL-em-eh",
    pos:        "verb",
    definition: ["wait"],
    tags:       ["intermediate", "verb"],
    examples:   [],
  },
  {
    word:       "antewe-irreme",
    phonetic:   "un-DEW-eh IR-rem-eh",
    pos:        "verb",
    definition: ["to vomit"],
    tags:       ["intermediate", "verb", "body"],
    examples:   [],
  },
  {
    word:       "arnteme",
    phonetic:   "arn-DEM-eh",
    pos:        "verb",
    definition: ["to ache"],
    tags:       ["intermediate", "verb", "body"],
    examples:   [],
  },
  {
    word:       "wangkeme",
    phonetic:   "WUNG-gem-eh",
    pos:        "verb",
    definition: ["swell up"],
    tags:       ["intermediate", "verb", "body"],
    examples:   [],
  },
  {
    word:       "arlkeme",
    phonetic:   "arl-GEM-eh",
    pos:        "verb",
    definition: ["shout out, call out, scream"],
    tags:       ["intermediate", "verb", "communication"],
    examples:   [],
  },
  {
    word:       "tnakeme",
    phonetic:   "DNAK-em-eh",
    pos:        "verb",
    definition: ["compliment, praise"],
    tags:       ["intermediate", "verb", "communication"],
    examples:   [],
  },
  {
    word:       "alyelheme",
    phonetic:   "ul-yel-HEM-eh",
    pos:        "verb",
    definition: ["sing (a song)"],
    tags:       ["intermediate", "verb", "culture"],
    examples:   [],
    notes:      "Also spelled ilyelheme in Eastern Arrernte",
  },
  {
    word:       "ilyelheme",
    phonetic:   "il-yel-HEM-eh",
    pos:        "verb",
    definition: ["sing (a song)"],
    tags:       ["intermediate", "verb", "culture"],
    examples:   [],
    notes:      "Eastern Arrernte form; Central form: alyelheme",
  },
  {
    word:       "artneme",
    phonetic:   "art-NEM-eh",
    pos:        "verb",
    definition: ["cry, bawl"],
    tags:       ["intermediate", "verb", "emotion"],
    examples:   [],
  },
  {
    word:       "atherreme",
    phonetic:   "ud-ERR-em-eh",
    pos:        "verb",
    definition: ["laugh, giggle, smile"],
    tags:       ["intermediate", "verb", "emotion"],
    examples:   [],
  },
  {
    word:       "awelheme",
    phonetic:   "uh-WEL-em-eh",
    pos:        "verb",
    definition: ["feel (some way)"],
    tags:       ["intermediate", "verb", "emotion"],
    examples:   [],
  },
  {
    word:       "wanteme",
    phonetic:   "WUN-dem-eh",
    pos:        "verb",
    definition: ["feed someone, serve"],
    tags:       ["intermediate", "verb", "food"],
    examples:   [],
  },
  {
    word:       "arrkene-irreme",
    phonetic:   "uh-RGEN-eh IR-rem-eh",
    pos:        "verb",
    definition: ["to play"],
    tags:       ["intermediate", "verb", "interaction"],
    examples:   [],
  },
  {
    word:       "anpere alheme",
    phonetic:   "un-BER-eh ul-HEM-eh",
    pos:        "verb",
    definition: ["pass by, go past"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "aparlpe-irreme",
    phonetic:   "ub-ARL-beh IR-rem-eh",
    pos:        "verb",
    definition: ["to get lost"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "arrtyaneme",
    phonetic:   "uh-RCHA-nem-eh",
    pos:        "verb",
    definition: ["run, run off"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "unteme",
    phonetic:   "OON-dem-eh",
    pos:        "verb",
    definition: ["run, hurry along"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "untheme",
    phonetic:   "OON-dem-eh",
    pos:        "verb",
    definition: ["look for, walk around"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "urtepe-irreme",
    phonetic:   "ort-EB-eh IR-rem-eh",
    pos:        "verb",
    definition: ["turn around to go back"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "alpeme",
    phonetic:   "ul-BEM-eh",
    pos:        "verb",
    definition: ["return, go back"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "apenteme",
    phonetic:   "ub-END-em-eh",
    pos:        "verb",
    definition: ["follow someone, follow a path"],
    tags:       ["intermediate", "verb", "movement"],
    examples:   [],
  },
  {
    word:       "akaltye-irreme",
    phonetic:   "ug-UL-cheh IR-rem-eh",
    pos:        "verb",
    definition: ["learn"],
    tags:       ["intermediate", "verb", "thinking"],
    examples:   [],
  },
  {
    word:       "akaltye-antheme",
    phonetic:   "ug-UL-cheh UN-dem-eh",
    pos:        "verb",
    definition: ["teach"],
    tags:       ["intermediate", "verb", "thinking"],
    examples:   [],
  },
  {
    word:       "anheme",
    phonetic:   "un-HEM-eh",
    pos:        "verb",
    definition: ["to rain, to water"],
    tags:       ["intermediate", "verb", "weather"],
    examples:   [],
  },
  {
    word:       "urinpe",
    phonetic:   "or-INB-eh",
    pos:        "adjective",
    definition: ["hot (thing or weather)"],
    tags:       ["intermediate", "weather", "describing"],
    examples:   [],
  },
  {
    word:       "irratye",
    phonetic:   "ir-RUCH-eh",
    pos:        "adjective",
    definition: ["cold, cold weather"],
    tags:       ["intermediate", "weather", "states"],
    examples:   [],
  },
];
